# Generated by Django 3.2.3 on 2021-05-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamDine', '0008_auto_20210517_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='COrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('delights', models.CharField(max_length=50)),
                ('tropics', models.CharField(max_length=50)),
                ('drinks', models.CharField(max_length=50)),
                ('dishes', models.CharField(max_length=50)),
                ('maincourse', models.CharField(max_length=50)),
                ('relishes', models.CharField(max_length=50)),
                ('paan', models.CharField(max_length=50)),
                ('desserts', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'COrder',
            },
        ),
    ]
