# Generated by Django 3.2.3 on 2021-05-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamDine', '0010_auto_20210517_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('mailid', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('food', models.CharField(max_length=50)),
                ('cleanliness', models.CharField(max_length=50)),
                ('ResponseTime', models.CharField(max_length=50)),
                ('recommend', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
        migrations.DeleteModel(
            name='order_cater',
        ),
    ]
