# Generated by Django 3.2.3 on 2021-05-17 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamDine', '0012_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('cart_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamDine.storeitems')),
            ],
            options={
                'db_table': 'Order_table',
            },
        ),
    ]
