# Generated by Django 3.2.3 on 2021-05-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamDine', '0013_order_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_items', models.CharField(max_length=200)),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'Orders_tables',
            },
        ),
        migrations.DeleteModel(
            name='Order_table',
        ),
    ]
