# Generated by Django 3.2.3 on 2021-05-18 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DreamDine', '0014_auto_20210518_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders_foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('cart_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DreamDine.storeitems')),
            ],
            options={
                'db_table': 'orders_foods',
            },
        ),
        migrations.DeleteModel(
            name='Orders_tables',
        ),
    ]
