# Generated by Django 3.2.3 on 2021-05-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamDine', '0015_auto_20210518_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='ritems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.URLField(max_length=300)),
            ],
            options={
                'db_table': 'ritems',
            },
        ),
    ]
