# Generated by Django 3.2.3 on 2021-05-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DreamDine', '0016_ritems'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('kind', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('newvar', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'recommendation',
            },
        ),
    ]
