

from django.urls import path
from . import views

urlpatterns=[
             path('index/',views.index),
path('',views.index,name='index'),
             path('login/',views.login),
path('cater/',views.cater),
path('table/',views.table),
             path('registers/',views.registers),
             path('userinfo/',views.userinfo),
             path('loginuser/',views.loginuser),
             path('menu/',views.menu),
path('add/',views.add),
path('add_contact/',views.add_contact),
path('feedback_add/',views.feedback_add),
path('additem/',views.additem),
path('add_table/',views.add_table),
path('pay_page/',views.pay_page),
path('deleteitem/<str:name>',views.deleteitem,name='deleteitem'),
path('remove/<str:name>',views.remove,name='remove'),
path('delete/',views.delete),
path('update/',views.update),
path('updateitem/', views.updateitem,name='updateitem'),
path('update_form/<str:name> <int:price>', views.update_form,name='update_form'),
path('productinfo/',views.productinfo),
path('ni/',views.ni),
path('si/',views.si),
path('search_add/',views.search_add),
path('sb/',views.sb),
path('about/',views.about),
path('contact/',views.contact),
path('addpayment/',views.addpayment),
path('end/',views.end),
path('amount/<int:total> <str:cart_items>/',views.amount,name='amount'),
path('order/',views.order),
path('sp/',views.sp),
path('dd/',views.dd),
path('ss/',views.ss),
path('italian/',views.italian),
path('ws/',views.ws),
path('pre_order/',views.pre_order),
path('goback/',views.goback),
path('logout/',views.logout),
path('forget_pwd/',views.forget_pwd),
path('fp/',views.fp),
path('cart_add/<str:name>/', views.cart_add, name='cart_add'),
path('cart_add_search/<str:name>/', views.cart_add_search, name='cart_add_search'),
path('cart_add_ritems/<str:name>/', views.cart_add_ritems, name='cart_add_ritems'),
path('get_cart_items/',views.get_cart_items),
#path('quantity/<str:name> <int:total>/',views.quantity,name='quantity'),
path('pay/',views.pay),
path('desserts/',views.desserts),
path('delights/',views.delights),
path('delights_add/',views.delights_add),
path('desserts_add/',views.desserts_add),
path('dishes_add/',views.dishes_add),
path('paan_add/',views.paan_add),
path('tropics_add/',views.tropics_add),
path('drinks_add/',views.drinks_add),
path('relishes_add/',views.relishes_add),
path('maincourse_add/',views.maincourse_add),
path('dishes/',views.dishes),
path('paan/',views.paan),
path('drinks/',views.drinks),
path('tropics/',views.tropics),
path('relishes/',views.relishes),
path('maincourse/',views.maincourse),
path('get_cater_items/',views.get_cater_items),
path('cater_order/' ,views.cater_order,name='cater_order'),
path('feedback/',views.feedback),
path('dummy/',views.dummy),
path('add_rec/',views.add_rec),
path('recomd/',views.recomd)
]
